Testes no banco de dados
dadosjusbr/verificador-integridade-dados pull request #1
Opened 2024-06-10 20:56 UTC by joellensilva

Vem sido discutido há algum tempo sobre a implementação de testes/checagens/alertas no banco de dados. Esse PR implementa as principais checagens discutidas utilizando a ferramenta DBT e Frictioless Framework e (considerando algumas limitações das ferramenta até atual conhecimento) em python. 
- Presença de caracteres numéricos ou especiais no nome
- Espaços no início e/ou fim ou duplos no nome
- Somatório da tabela de remunerações é igual a tabela de coletas
- Cálculo correto do contracheque individual
- Remuneração líquida negativa
- Um único membro ter 14 lançamentos ou mais no mesmo mês (apenas remunerações, base ou outras), com valores diferentes de zero e diferentes de nulo, no mesmo órgão.
- Valor total (soma de todas as remunerações de todos os membros) do órgão, naquele mês, 50% superior à média mensal daquele órgão no ano anterior.
- Valor total (soma de todas as remunerações de todos os membros) de um mês, para cada órgão, 50% inferior à média mensal daquele órgão no ano anterior. 
- Número de membros de cada órgão (count unique) representar menos de 50% da média de membros daquele órgão no ano anterior.
- Comparação do somatório da base por categoria com as rubricas consolidadas do CNJ (direitos-pessoais, direitos-eventuais, indenizações e total de descontos.

Dessa forma, esse PR implementa testes voltados para o banco de dados, e, enquanto estágio, para os pacotes de dados gerados nas coletas.

2024-06-11 20:30 UTC, JezzDiego commented
Bastante coisa mesmo. Me parece OK.

2024-07-15 12:39 UTC, danielfireman requested changes

2024-07-15 12:39 UTC, danielfireman commented on src/main.py
> +        expect_R_B_to_equal_summary,
Muito legal a abordagem, porém ler o mesmo CSV múltiplas vezes me parece bem ruim. Não seria melhor passar o pandas data frame como parâmetro? Daí ele só precisaria ser criado uma vez.

2024-07-15 17:12 UTC, joellensilva commented on src/main.py
> +        expect_R_B_to_equal_summary,
Verdade!

2024-07-15 18:16 UTC, joellensilva commented on src/main.py
> +        expect_R_B_to_equal_summary,
Feito!

2024-07-15 18:33 UTC, danielfireman approved these changes

2024-07-15 18:46 UTC, merged